### ISSUE TITLE
Bug in exportToPhy

### ISSUE THREAD

**Issue by colehurwitz31** [alejoe91/spiketoolkit#19]
Ran into this error when running exportToPhy in the mountainsort example notebook. I used the local install of spiketoolkit this time.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-9251dc7c500b> in <module>
----> 1 st.exportToPhy(recording, sorting, output_folder='mountainsort')

~/miniconda3/envs/mountainsort/lib/python3.7/site-packages/spiketoolkit-0.1.4-py3.7.egg/spiketoolkit/tools.py in exportToPhy(recording, sorting, output_folder, nPCchan, nPC, filter, electrode_dimensions)
     34 
     35     # pc_features.npy - [nSpikes, nFeaturesPerChannel, nPCFeatures] single
---> 36     pc_scores = analyzer.computePCAscores(n_comp=nPC, elec=True)
     37 
     38     # spike times.npy and spike clusters.npy

~/miniconda3/envs/mountainsort/lib/python3.7/site-packages/spiketoolkit-0.1.4-py3.7.egg/spiketoolkit/analyzer/analyzer.py in computePCAscores(self, n_comp, elec)
    257 
    258         pca = PCA(n_components=n_comp, whiten=True)
--> 259         pca.fit_transform(all_waveforms)
    260         scores = pca.transform(all_waveforms)
    261 

~/miniconda3/envs/mountainsort/lib/python3.7/site-packages/scikit_learn-0.20.0-py3.7-linux-x86_64.egg/sklearn/decomposition/pca.py in fit_transform(self, X, y)
    357 
    358         """
--> 359         U, S, V = self._fit(X)
    360         U = U[:, :self.n_components_]
    361 

~/miniconda3/envs/mountainsort/lib/python3.7/site-packages/scikit_learn-0.20.0-py3.7-linux-x86_64.egg/sklearn/decomposition/pca.py in _fit(self, X)
    379 
    380         X = check_array(X, dtype=[np.float64, np.float32], ensure_2d=True,
--> 381                         copy=self.copy)
    382 
    383         # Handle n_components==None

~/miniconda3/envs/mountainsort/lib/python3.7/site-packages/scikit_learn-0.20.0-py3.7-linux-x86_64.egg/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    545                     "Reshape your data either using array.reshape(-1, 1) if "
    546                     "your data has a single feature or array.reshape(1, -1) "
--> 547                     "if it contains a single sample.".format(array))
    548 
    549         # in the future np.flexible dtypes will be handled like object dtypes

ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by alejoe91** [comment]
Hi @colehurwitz31, just seen this. It was a stupit error: I had `self._waveforms` instead of `self.getUnitWaveform()`, so if waveforms were not computed before it was an empty list...should be fixed with latest commit
